use failure alert approach

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -49,29 +49,16 @@ jobs:
         run: |
           task test
 
-  run-tests-status-check:
-    runs-on: ubuntu-24.04
-    if: always()
+  # This workflow gets skipped if all upstream jobs succeeded, but it runs (and fails) if any upstream failed.
+  # This is what we want since GitHub required actions do not block merging when skipped, but can block it when failed.
+  # See: https://github.com/actions/runner/issues/2566#issuecomment-3053484216
+  run-tests-failure-alert:
+    runs-on: ubuntu-latest
     needs: [filter, run-tests]
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
     steps:
-      - name: Run Tests Status Check
+      - name: NoGood
+        shell: bash
         run: |
-          svcs='${{ needs.filter.outputs.services }}'
-
-          echo "services=${svcs}"
-          echo "run-tests.result=${{ needs.run-tests.result }}"
-
-          # If no services changed, treat as success (no tests to run)
-          if [[ -z "$svcs" || "$svcs" == "[]" ]]; then
-            echo "No matching services changed; passing status check."
-            exit 0
-          fi
-
-          # Otherwise, require the matrix job to have succeeded
-          if [[ "${{ needs.run-tests.result }}" == "success" ]]; then
-            echo "All test matrix jobs passed."
-            exit 0
-          else
-            echo "::error One or more test matrix jobs failed or were cancelled."
-            exit 1
-          fi
+          echo "Some workflows have failed!"
+          exit 1
